name: release

on:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to quay.io container registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./cluster/addons/fluentd-elasticsearch/fluentd-es-image
          file: ./cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/monotek/fluentd-elasticsearch:${{ github.run_number }}
            quay.io/monotek/fluentd-elasticsearch:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
